import torch
CONFIG= {
    'learning_rate': 0.001,
    'embedding_dim': 300,
    'hidden_dim': 200,
    'batch_size': 50,
    'num_clusters': 20,
    'epoch': 3,
    'random_seed': 100,
    'task_memory_size': 100,
    'loss_margin': 0.5,
    'num_cands': 10,
    'sequence_times': 5,
    'model_path': 'model.pt',
    'device': torch.device('cuda:1' if torch.cuda.is_available() else 'cpu'),
    'relation_file': '../ewc/data/relation_name.txt',
    'training_file': '../ewc/data/training_data.txt',
    'test_file': '../ewc/data/val_data.txt',
    'valid_file': '../ewc/data/val_data.txt',
    #'training_file': './data/train.replace_ne.withpool',
    #'test_file': './data/test.replace_ne.withpool',
    #'valid_file': './data/valid.replace_ne.withpool',
    'glove_file': '../ewc/data/glove.6B.300d.txt',
}
